version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my_network

  app:
    image: driveanddeliver-app:cloud
    container_name: driveanddeliver-app
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: cloud
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
